version: '2'

networks:
  prodnetwork:
    driver: bridge

services:
 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /opt/jenkins/:/var/lib/jenkins
