=== Step 2 - Adding Jenkins plugins

Ok, now we are going to add a file containing some plugins, which will be loaded automatically by Jenkins.
Create a `plugins.txt` file inside the `jenkins` directory. Now let's
populate it with a bunch of
https://raw.githubusercontent.com/sebivenlo/jenkins/e7bc3c2fd433b926e1c602056c3470cb7f6915d6/jenkins/plugins.txt[plugins],
which we will need during this workshop.

[NOTE]
If you have a browser plugin to render your adoc pages, you may want to download (right-click, download) the plugins.txt file instead of opening it with the browser, because said plugin will almost certainly mess up the text.

When we create the Jenkins container, we now also need to ensure that Jenkins knows about the plugins that we just defined. In order to do that, we need to move the plugins file to `/usr/local/bin/install-plugins.sh`. So let's add that to our `Dockerfile`. Insert the following two lines *before* the last line of our `Dockerfile`:

```
COPY plugins.txt /var/jenkins_home/plugins.txt
RUN /usr/local/bin/install-plugins.sh $(cat /var/jenkins_home/plugins.txt | tr -d '\r' | tr '\n' ' ')
```

Since that we changed the Docker configuration, we need to rebuild the image for Jenkins. Let's first remove the Jenkins container. Use `docker ps -a` to get the names and ID's of all the containers for the current Docker machine. Next remove the container by using the following command: `docker rm -f <jenkins container id>`. Now we have to recreate the image by doing `docker-compose build`, followed by a `docker-compose up -d`. These changes should now be applied to our Jenkins environment.
